# Generated by Django 2.2.2 on 2019-06-29 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('location', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_settled', models.BooleanField(default=False)),
                ('complaint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('ref_image', models.ImageField(default=None, upload_to='Complaints')),
                ('tag', models.CharField(choices=[('Accident', 'Accident'), ('Disaster', 'Natural Disaster'), ('Roads', 'Road Maintenance'), ('Other', 'Other')], max_length=9)),
                ('description', models.TextField()),
                ('complaint_status', models.CharField(max_length=10)),
                ('filer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
