# Generated by Django 2.2.3 on 2019-07-07 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('location', models.URLField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_settled', models.BooleanField(default=False)),
                ('complaint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('ref_image', models.ImageField(default=None, upload_to='Complaints')),
                ('type_of_complaint', models.CharField(choices=[('Accident', 'Accident'), ('Disaster', 'Natural Disaster'), ('Roads', 'Road Maintenance'), ('Other', 'Other')], max_length=9)),
                ('description', models.TextField()),
                ('complaint_status', models.CharField(max_length=10)),
                ('filer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(related_name='complaints', to='mun_dashboard.Tag')),
            ],
        ),
    ]
