# Generated by Django 2.2.3 on 2019-07-08 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('location', models.URLField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_settled', models.BooleanField(default=False)),
                ('complaint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_filed', models.DateTimeField(auto_now_add=True, null=True)),
                ('ref_image', models.ImageField(default=None, upload_to='Complaints')),
                ('type_of_complaint', models.CharField(choices=[('Accident', 'Accident'), ('Disaster', 'Natural Disaster'), ('Roads', 'Road Maintenance'), ('Other', 'Other')], max_length=9)),
                ('description', models.TextField()),
                ('complaint_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('reward', models.IntegerField()),
            ],
        ),
    ]
