# Generated by Django 2.2.3 on 2019-07-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_filed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
