# Generated by Django 2.2.3 on 2019-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_dashboard', '0002_auto_20190707_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_filed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
