# Generated by Django 2.2.3 on 2019-07-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_dashboard', '0002_auto_20190708_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
