# Generated by Django 2.2.3 on 2019-07-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_dashboard', '0003_auto_20190711_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='Compalints')),
                ('name', models.CharField(max_length=11)),
            ],
        ),
    ]
