# Generated by Django 2.2.3 on 2019-07-12 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mun_dashboard', '0005_auto_20190712_0454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
