# Generated by Django 2.2.3 on 2019-07-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_dashboard', '0006_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
