# Generated by Django 2.2.3 on 2019-07-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_dashboard', '0007_auto_20190712_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
